version: "3.9"  # optional since v1.27.0
services:
  server-v1:
    build: ./server-v1
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
  server-v2:
    build: ./server-v2
    ports:
      - "4000:4000"
    environment:
      PORT: 4000
